name: "Delete GitHub Actions cache"
description: "Delete GitHub Actions cache"
inputs:
  github-token:
    description: GitHub token
    default: ${{ github.token }}
    required: false
outputs:
  runs:
    using: "composite"
  steps:
    - 
      run: |
        gh extension install actions/gh-actions-cache

        mergedPRNumbers=$(gh pr list --state merged --json number | jq .[].number)

        for prNumber in $mergedPRNumbers
        do
          gh actions-cache list -B refs/pull/$prNumber/merge | cut -f 1 | xargs -I{} gh actions-cache delete --confirm {}
        done
